### ISSUE TITLE
The discount should be an optional field on Transaction Complete API

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-financial-manager#252]
Internal error receiving transaction on financial manager:
```bash
root@nau02-dev:/nau/ops/financial_manager# make logs
```

```bash
financial_manager_app    | The above exception was the direct cause of the following exception:
financial_manager_app    |
financial_manager_app    | Traceback (most recent call last):
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
financial_manager_app    |     response = get_response(request)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
financial_manager_app    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
financial_manager_app    |     return view_func(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
financial_manager_app    |     return self.dispatch(request, *args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
financial_manager_app    |     response = self.handle_exception(exc)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
financial_manager_app    |     self.raise_uncaught_exception(exc)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
financial_manager_app    |     raise exc
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
financial_manager_app    |     response = handler(request, *args, **kwargs)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/util/base_views.py", line 264, in post
financial_manager_app    |     serializer.save()
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
financial_manager_app    |     self.instance = self.create(validated_data)
financial_manager_app    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 162, in create
financial_manager_app    |     raise e
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 147, in create
financial_manager_app    |     transaction, items = self._execute_billing_resources(validate_data=validate_data)
financial_manager_app    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 138, in _execute_billing_resources
financial_manager_app    |     item = TransactionItem.objects.create(**item)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
financial_manager_app    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
financial_manager_app    |     obj.save(force_insert=True, using=self.db)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/safedelete/models.py", line 131, in save
financial_manager_app    |     super(SafeDeleteModel, self).save(**kwargs)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
financial_manager_app    |     self.save_base(
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
financial_manager_app    |     updated = self._save_table(
financial_manager_app    |               ^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
financial_manager_app    |     results = self._do_insert(
financial_manager_app    |               ^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
financial_manager_app    |     return manager._insert(
financial_manager_app    |            ^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
financial_manager_app    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
financial_manager_app    |     return query.get_compiler(using=using).execute_sql(returning_fields)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
financial_manager_app    |     cursor.execute(sql, params)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
financial_manager_app    |     return self._execute_with_wrappers(
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
financial_manager_app    |     return executor(sql, params, many, context)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
financial_manager_app    |     with self.db.wrap_database_errors:
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
financial_manager_app    |     raise dj_exc_value.with_traceback(traceback) from exc_value
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
financial_manager_app    |     return self.cursor.execute(sql, params)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
financial_manager_app    |     return self.cursor.execute(query, args)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
financial_manager_app    |     res = self._query(mogrified_query)
financial_manager_app    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
financial_manager_app    |     db.query(q)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
financial_manager_app    |     _mysql.connection.query(self, query)

financial_manager_app    | django.db.utils.OperationalError: (1054, "Unknown column 'discount' in 'field list'")
financial_manager_app    | Internal Server Error: /api/billing/transaction-complete/
financial_manager_app    | Traceback (most recent call last):
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
financial_manager_app    |     return self.cursor.execute(sql, params)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
financial_manager_app    |     return self.cursor.execute(query, args)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
financial_manager_app    |     res = self._query(mogrified_query)
financial_manager_app    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
financial_manager_app    |     db.query(q)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
financial_manager_app    |     _mysql.connection.query(self, query)
financial_manager_app    | MySQLdb.OperationalError: (1054, "Unknown column 'discount' in 'field list'")
financial_manager_app    |
financial_manager_app    | The above exception was the direct cause of the following exception:
financial_manager_app    |
financial_manager_app    | Traceback (most recent call last):
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
financial_manager_app    |     response = get_response(request)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
financial_manager_app    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
financial_manager_app    |     return view_func(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
financial_manager_app    |     return self.dispatch(request, *args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
financial_manager_app    |     response = self.handle_exception(exc)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
financial_manager_app    |     self.raise_uncaught_exception(exc)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
financial_manager_app    |     raise exc
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
financial_manager_app    |     response = handler(request, *args, **kwargs)
financial_manager_app    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/util/base_views.py", line 264, in post
financial_manager_app    |     serializer.save()
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
financial_manager_app    |     self.instance = self.create(validated_data)
financial_manager_app    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 162, in create
financial_manager_app    |     raise e
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 147, in create
financial_manager_app    |     transaction, items = self._execute_billing_resources(validate_data=validate_data)
financial_manager_app    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/app/apps/billing/serializers.py", line 138, in _execute_billing_resources
financial_manager_app    |     item = TransactionItem.objects.create(**item)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
financial_manager_app    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 658, in create
financial_manager_app    |     obj.save(force_insert=True, using=self.db)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/safedelete/models.py", line 131, in save
financial_manager_app    |     super(SafeDeleteModel, self).save(**kwargs)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
financial_manager_app    |     self.save_base(
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
financial_manager_app    |     updated = self._save_table(
financial_manager_app    |               ^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
financial_manager_app    |     results = self._do_insert(
financial_manager_app    |               ^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
financial_manager_app    |     return manager._insert(
financial_manager_app    |            ^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
financial_manager_app    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
financial_manager_app    |     return query.get_compiler(using=using).execute_sql(returning_fields)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
financial_manager_app    |     cursor.execute(sql, params)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
financial_manager_app    |     return self._execute_with_wrappers(
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
financial_manager_app    |     return executor(sql, params, many, context)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
financial_manager_app    |     with self.db.wrap_database_errors:
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
financial_manager_app    |     raise dj_exc_value.with_traceback(traceback) from exc_value
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
financial_manager_app    |     return self.cursor.execute(sql, params)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
financial_manager_app    |     return self.cursor.execute(query, args)
financial_manager_app    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
financial_manager_app    |     res = self._query(mogrified_query)
financial_manager_app    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
financial_manager_app    |     db.query(q)
financial_manager_app    |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
financial_manager_app    |     _mysql.connection.query(self, query)
financial_manager_app    | django.db.utils.OperationalError: (1054, "Unknown column 'discount' in 'field list'")
```

**Comment by igobranco** [comment]
The problem is related to the new `discount` information.

**Comment by igobranco** [comment]
Related to https://github.com/fccn/ecommerce-nau-extensions/issues/3

**Comment by igobranco** [comment]
Currently the discount isn't optional on the Transaction Complete API.
