### ISSUE TITLE
financial manager app job restarting in loop

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-financial-manager#306]
```
financial_manager_app_job  | Operations to perform:
financial_manager_app_job  |   Apply all migrations: admin, auditlog, auth, authtoken, billing, contenttypes, django_celery_beat, django_celery_results, organization, sessions, shared_revenue, util
financial_manager_app_job  | Running migrations:
financial_manager_app_job  | Traceback (most recent call last):
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
financial_manager_app_job  |     return self.cursor.execute(sql, params)
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
financial_manager_app_job  |     return self.cursor.execute(query, args)
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
financial_manager_app_job  |     res = self._query(mogrified_query)
financial_manager_app_job  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
financial_manager_app_job  |     db.query(q)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
financial_manager_app_job  |     _mysql.connection.query(self, query)
financial_manager_app_job  | MySQLdb.OperationalError: (1060, "Duplicate column name 'discount'")
financial_manager_app_job  |
financial_manager_app_job  | The above exception was the direct cause of the following exception:
financial_manager_app_job  |
financial_manager_app_job  | Traceback (most recent call last):
financial_manager_app_job  |   File "/app/manage.py", line 22, in <module>
financial_manager_app_job  |     main()
financial_manager_app_job  |   File "/app/manage.py", line 18, in main
financial_manager_app_job  |     execute_from_command_line(sys.argv)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
financial_manager_app_job  |     utility.execute()
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
financial_manager_app_job  |     self.fetch_command(subcommand).run_from_argv(self.argv)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
financial_manager_app_job  |     self.execute(*args, **cmd_options)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
financial_manager_app_job  |     output = self.handle(*args, **options)
financial_manager_app_job  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
financial_manager_app_job  |     res = handle_func(*args, **kwargs)
financial_manager_app_job  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
financial_manager_app_job  |     post_migrate_state = executor.migrate(
financial_manager_app_job  |                          ^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
financial_manager_app_job  |     state = self._migrate_all_forwards(
financial_manager_app_job  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
financial_manager_app_job  |     state = self.apply_migration(
financial_manager_app_job  |             ^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
financial_manager_app_job  |     state = migration.apply(state, schema_editor)
financial_manager_app_job  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
financial_manager_app_job  |     operation.database_forwards(
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards
financial_manager_app_job  |     schema_editor.add_field(
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/schema.py", line 107, in add_field
financial_manager_app_job  |     super().add_field(model, field)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 713, in add_field
financial_manager_app_job  |     self.execute(sql, params)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
financial_manager_app_job  |     cursor.execute(sql, params)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
financial_manager_app_job  |     return self._execute_with_wrappers(
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
financial_manager_app_job  |     return executor(sql, params, many, context)
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
financial_manager_app_job  |     with self.db.wrap_database_errors:
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
financial_manager_app_job  |     raise dj_exc_value.with_traceback(traceback) from exc_value
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
financial_manager_app_job  |     return self.cursor.execute(sql, params)
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/base.py", line 75, in execute
financial_manager_app_job  |     return self.cursor.execute(query, args)
financial_manager_app_job  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
financial_manager_app_job  |     res = self._query(mogrified_query)
financial_manager_app_job  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
financial_manager_app_job  |     db.query(q)
financial_manager_app_job  |   File "/usr/local/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
financial_manager_app_job  |     _mysql.connection.query(self, query)
financial_manager_app_job  | django.db.utils.OperationalError: (1060, "Duplicate column name 'discount'")
financial_manager_app_job  |   Applying billing.0002_transactionitem_discount...wait-for-it: waiting 15 seconds for 172.22.1.49:13306
f
```

**Comment by igobranco** [comment]
The migration have been applied, but not registered as done.
```bash
python manage.py migrate --fake billing 0002_transactionitem_discount
```
