### ISSUE TITLE
Error reading receipt link when iLink without that doc

### ISSUE THREAD

**Issue by igobranco** [fccn/nau-financial-manager#320]
When the Financial Manager has a Transaction on its database.
But Sage hasn't sent it to iLink.
The Financial Manager receipt link API web method returns an error instead of returning not found.

We need to add a test for this situation, add a mock return of iLink without any document and / or any PDF document.
Fix this condition.

**Comment by igobranco** [comment]
```bash
curl -v -X 'GET' 'https://financial-manager.stage.nau.fccn.pt/api/billing/receipt-link/OPENEDX-100077/'  -H 'accept: application/json' -H 'Authorization: Token XXXXXXXXXXXXXXX'

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 193.136.192.179:443...
* Connected to financial-manager.stage.nau.fccn.pt (193.136.192.179) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=PT; ST=Lisboa; O=Fundacao para a Ciencia e a Tecnologia I.P; CN=financial-manager.stage.nau.fccn.pt
*  start date: Nov 29 00:00:00 2023 GMT
*  expire date: Nov 28 23:59:59 2024 GMT
*  subjectAltName: host "financial-manager.stage.nau.fccn.pt" matched cert's "financial-manager.stage.nau.fccn.pt"
*  issuer: C=NL; O=GEANT Vereniging; CN=GEANT OV RSA CA 4
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x55b811947eb0)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /api/billing/receipt-link/OPENEDX-100077/ HTTP/2
> Host: financial-manager.stage.nau.fccn.pt
> user-agent: curl/7.81.0
> accept: application/json
> authorization: Token 67862ac1bcfa071cd5e559de8b2cf3371e056529
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 500
< server: nginx/1.20.1
< date: Tue, 29 Oct 2024 15:18:35 GMT
< content-type: application/json
< content-length: 64
< allow: GET, OPTIONS
< x-frame-options: DENY
< vary: Cookie
< x-content-type-options: nosniff
< referrer-policy: same-origin
< cross-origin-opener-policy: same-origin
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-backend-server: nau02-qa.nau.fccn.pt
<
* Connection #0 to host financial-manager.stage.nau.fccn.pt left intact
{"response":"A not expected error ocurred getting the document"}
```

Stack trace:
```
financial_manager_app  | Not expected error ocurred getting the document
financial_manager_app  | Traceback (most recent call last):
financial_manager_app  |   File "/app/apps/billing/views.py", line 64, in get_receipt_link
financial_manager_app  |     receipt_link = ReceiptDocumentHost().get_document(document_id=transaction.document_id)
financial_manager_app  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
financial_manager_app  |   File "/app/apps/billing/services/receipt_host_service.py", line 34, in get_document
financial_manager_app  |     document_informations = [
financial_manager_app  |                             ^
financial_manager_app  | IndexError: list index out of range
financial_manager_app  | Internal Server Error: /api/billing/receipt-link/OPENEDX-100077/
```

https://github.com/fccn/nau-financial-manager/blob/02973abefdfcfa96745dc3c3f194f1ef28bf3e87/apps/billing/services/receipt_host_service.py#L34

It could be related that there is a receipt document on the iLink service, but still without a PDF document. The PDF doc it being issued asynchronously and the sent to iLink.
